public class Main{
    public static void main(String[]args){
        int age=25;
        String str="Welcome to kunemadihalli";
        char c='A';
        boolean be=true;
        double d=500000;
        System.out.println("age:" +age);
        System.out.println("str:" +str);
        System.out.println("c:" +c);
        System.out.println("be:" +be);
        System.out.println("d:" +d);
    }
}
